portais = {
    'diarioaco_mg': {
        'abrangencia': 'Local',
        'nome': 'Diário do Aço (MG)',
        'url': 'https://www.diariodoaco.com.br/minas',
        'prioridade': 'Alta',
        'pontos': 8,
    },
    'diarioaco': {
        'abrangencia': 'Local',
        'nome': 'Diário do Aço',
        'url': 'https://www.diariodoaco.com.br/',
        'prioridade': 'Alta',
        'pontos': 8,
    },
    'correio_mg': {
        'abrangencia': 'Nacional',
        'nome': 'Correio de Minas (MG)',
        'url': 'https://correiodeminas.com.br/',
        'prioridade': 'Baixa',
        'pontos': 6,
    },
    'otempo_ultimas': {
        'abrangencia': 'Local',
        'nome': 'O Tempo',
        'url': 'https://www.otempo.com.br/',
        'prioridade': 'Alta',
        'pontos': 20,
    },
    'itatiaia_ultimas': {
        'abrangencia': 'Local',
        'nome': 'Itatiaia (MG)',
        'url': 'https://www.itatiaia.com.br/',
        'prioridade': 'Alta',
        'pontos': 20,
    },
   'plox_ultimas': {
        'abrangencia': 'Regional',
        'nome': 'Plox Últimas',
        'url': 'https://plox.com.br/ipatinga/ultimas-noticias',
        'prioridade': 'Alta',
        'pontos': 8,
   },
    'g1_mg': {
        'abrangencia': 'Local',
        'nome': 'G1 Minas',
        'url': 'https://g1.globo.com/mg/minas-gerais/',
        'prioridade': 'Alta',
        'pontos': '15'
    },
    'g1': {
        'abrangencia': 'Nacional',
        'nome': 'G1',
        'url': 'https://g1.globo.com/',
        'prioridade': 'Alta',
        'pontos': '35'
    },
    'globo': {
        'abrangencia': 'Nacional',
        'nome': 'Globo',
        'url': 'https://globo.com',
        'prioridade': 'Alta',
        'pontos': '10'
    },
    'g1_fantastico': {
        'abrangencia': 'Nacional',
        'nome': 'Fantástico',
        'url': 'https://g1.globo.com/fantastico/',
        'prioridade': 'Alta',
        'pontos': '50',
    },
    'g1_jn': {
        'abrangencia': 'Nacional',
        'nome': 'Jornal Nacional',
        'url': 'https://g1.globo.com/jornal-nacional/',
        'prioridade': 'Alta',
        'pontos': '50',
    },
    'oglobo_mg': {
        'abrangencia': 'Nacional',
        'nome': 'Portal O Globo',
        'url': 'https://oglobo.globo.com/brasil/minas-gerais/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    'oglobo': {
        'abrangencia': 'Nacional',
        'nome': 'Portal O Globo',
        'url': 'https://oglobo.globo.com/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    'uol_mg': {
        'abrangencia': 'Nacional',
        'nome': 'Portal UOL (MG)',
        'url': 'https://noticias.uol.com.br/minas-gerais/noticias/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    'uol': {
        'abrangencia': 'Nacional',
        'nome': 'Portal UOL',
        'url': 'https://www.uol.com.br/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    'pocosja': {
        'abrangencia': 'Regional',
        'nome': 'Portal Poços Já',
        'url': 'https://pocosja.com.br/',
        'prioridade': 'Alta',
        'pontos': '6',
    },
    'band_mg': {
        'abrangencia': 'Local',
        'nome': 'Portal Band Minas',
        'url': 'https://www.band.uol.com.br/minas-gerais',
        'prioridade': 'Média',
        'pontos': '7',
    },
    'cultura': {
        # nao esta na planilha de monitoramento
        'abrangencia': 'Nacional',
        'nome': 'TV Cultura',
        'url': 'https://cultura.uol.com.br/eleicoes/',
        'prioridade': 'Alta',
        'pontos': '15',
    },
    'hjdia_mg': {
        'abrangencia': 'Local',
        'nome': 'Hoje em Dia (MG)',
        'url': 'https://www.hojeemdia.com.br/minas',
        'prioridade': 'Alta',
        'pontos': '12',
    },
    'hjdia': {
        'abrangencia': 'Local',
        'nome': 'Hoje em Dia',
        'url': 'https://www.hojeemdia.com.br/',
        'prioridade': 'Alta',
        'pontos': '12',
    },
    'veja': {
        'abrangencia': 'Nacional',
        'nome': 'Veja Abril',
        'url': 'https://veja.abril.com.br/',
        'prioridade': 'Média',
        'pontos': '35',
    },
    'cnn': {
        'abrangencia': 'Nacional',
        'nome': 'CNN',
        'url': 'https://www.cnnbrasil.com.br/',
        'prioridade': 'Média',
        'pontos': '20',
    },
    'cnn_mg': {
        'abrangencia': 'Nacional',
        'nome': 'CNN (MG)',
        'url': 'https://www.cnnbrasil.com.br/tudo-sobre/minas-gerais/',
        'prioridade': 'Média',
        'pontos': '20',
    },
    'metropoles': {
        'abrangencia': 'Nacional',
        'nome': 'Metrópoles',
        'url': 'https://www.metropoles.com/',
        'prioridade': 'Alta',
        'pontos': '20',  
    },
    'terra': {
        'abrangencia': 'Nacional',
        'nome': 'Terra',
        'url': 'https://www.terra.com.br/ultimas/',
        'prioridade': 'Média',
        'pontos': '20',
    },
    'poder': {
        'abrangencia': 'Nacional',
        'nome': 'Poder 360',
        'url': 'https://www.poder360.com.br/poder-hoje/',
        'prioridade': 'Média',
        'pontos': '15',
    },
    'poder_mg': {
        'abrangencia': 'Nacional',
        'nome': 'Poder 360',
        'url': 'https://www.poder360.com.br/tag/minas-gerais/',
        'prioridade': 'Média',
        'pontos': '15',
    },
    'aqui_mg': {
        'abrangencia': 'Local',
        'nome': 'Aqui (MG)',
        'url': 'https://aqui.uai.com.br/',
        'prioridade': 'Baixa',
        'pontos': '20',
    },
    'estadao': {
        'abrangencia': 'Nacional',
        'nome': 'Estadão',
        'url': 'https://www.estadao.com.br/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    'braziliense': {
        'abrangencia': 'Nacional',
        'nome': 'Correio Braziliense',
        'url': 'https://www.correiobraziliense.com.br/',
        'prioridade': 'Baixa',
        'pontos': '15',
    },
    'braziliense_mg': {
        'abrangencia': 'Nacional',
        'nome': 'Correio Braziliense',
        'url': 'https://www.correiobraziliense.com.br/',
        'prioridade': 'Baixa',
        'pontos': '15',
    },
    'onda_sul': {
        'abrangencia': 'Regional',
        'nome': 'Onda Sul',
        'url': 'https://www.portalondasul.com.br/',
        'prioridade': 'Alta',
        'pontos': '8',
    },
    'sbt': {
        'abrangencia': 'Nacional',
        'nome': 'SBT News',
        'url': 'https://sbtnews.sbt.com.br/',
        'prioridade': 'Média', # não é certeza pois não estava na planilha
        'pontos': '20',
    },
    'band_uol': {
        'abrangencia': 'Nacional',
        'nome': 'Band Uol',
        'url': 'https://www.band.uol.com.br/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'record_news': {
        'abrangencia': 'Nacional',
        'nome': 'Record News',
        'url': 'https://noticias.r7.com/record-news/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'r7_mg': {
        'abrangencia': 'Regional',
        'nome': 'R7 Minas Gerais',
        'url': 'https://noticias.r7.com/minas-gerais/',
        'prioridade': 'Média',
        'pontos': '7',
    },
    'record': {
        'abrangencia': 'Nacional',
        'nome': 'R7',
        'url': 'https://www.r7.com/',
        'prioridade': 'Média',
        'pontos': 20,
    },
    'r7_noticias': {
        'abrangencia': 'Nacional',
        'nome': 'JR 24H',
        'url': 'https://noticias.r7.com/',
        'prioridade': 'Média',
        'pontos': '30',
    },
    'agbrasil': {
        'abrangencia': 'Nacional',
        'nome': 'Agência Brasil',
        'url': 'https://agenciabrasil.ebc.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '10',
    },
    'bbc': {
        'abrangencia': 'Nacional',
        'nome': 'Portal BBC',
        'url': 'https://www.bbc.com/portuguese',
        'prioridade': 'Baixa', 
        'pontos': '10',
    },
    'jovempan_mg': {
        'abrangencia': 'Nacional',
        'nome': 'Jovem Pan MG',
        'url': 'https://jovempan.com.br/tag/minas-gerais',
        'prioridade': 'Média',
        'pontos': '20',
    },
    'jovempan': {
        'abrangencia': 'Nacional',
        'nome': 'Jovem Pan',
        'url': 'https://jovempan.com.br/',
        'prioridade': 'Média',
        'pontos': '20',
    },
    'gazeta': {
        'abrangencia': 'Regional',
        'nome': 'Gazeta do Povo',
        'url': 'https://www.gazetadopovo.com.br/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'intercept': {
        'abrangencia': 'Nacional',
        'nome': 'The Intercept',
        'url': 'https://www.intercept.com.br/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'folha': {
        'abrangencia': 'Nacional',
        'nome': 'Folha de SP',
        'url': 'https://www1.folha.uol.com.br/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    'exame': {
        'abrangencia': 'Nacional',
        'nome': 'Revista Exame',
        'url': 'https://exame.com/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'istoe': {
        'abrangencia': 'Nacional',
        'nome': 'Revista Isto É',
        'url': 'https://istoe.com.br/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'bandnews': {
        'abrangencia': 'Nacional',
        'nome': 'Rádio Band News',
        'url': 'https://www.band.uol.com.br/bandnews-fm/noticias',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'bandnews_bh': {
        'abrangencia': 'Local',
        'nome': 'Rádio Band News (BH)',
        'url': 'https://www.band.uol.com.br/bandnews-fm/belo-horizonte',
        'prioridade': 'Média',
        'pontos': '7',
    },
    'cbn': {
        'abrangencia': 'Nacional',
        'nome': 'Rádio CBN Nacional',
        'url': 'https://cbn.globo.com/',
        'prioridade': 'Média',
        'pontos': '10',
    },
    'brasilfato': {
        'abrangencia': 'Nacional',
        'nome': 'Brasil de Fato',
        'url': 'https://www.brasildefato.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'cartacapital': {
        'abrangencia': 'Nacional',
        'nome': 'Brasil de Fato',
        'url': 'https://www.cartacapital.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'congressofoco': {
        'abrangencia': 'Nacional',
        'nome': 'Congresso em Foco',
        'url': 'https://congressoemfoco.uol.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'jota': {
        'abrangencia': 'Nacional',
        'nome': 'Jota',
        'url': 'https://www.jota.info/',
        'prioridade': 'Baixa',
        'pontos': '15',
    },
    'canalrural': {
        'abrangencia': 'Nacional',
        'nome': 'Canal Rural',
        'url': 'https://www.canalrural.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'camara': {
        'abrangencia': 'Nacional',
        'nome': 'Câmara Federal',
        'url': 'https://www.camara.leg.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'ghzgaucha': {
        'abrangencia': 'Nacional',
        'nome': 'GHZ Gaucha',
        'url': 'https://gauchazh.clicrbs.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'senado': {
        'abrangencia': 'Nacional',
        'nome': 'Senado',
        'url': 'https://www12.senado.leg.br/noticias',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'infomoney': {
        'abrangencia': 'Nacional',
        'nome': 'InfoMoney',
        'url': 'https://www.infomoney.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'moneytimes': {
        'abrangencia': 'Nacional',
        'nome': 'Money Times',
        'url': 'https://www.moneytimes.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'piaui': {
        'abrangencia': 'Nacional',
        'nome': 'Revista Piauí',
        'url': 'https://piaui.folha.uol.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    'portal24h': {
        'abrangencia': 'Regional',
        'nome': 'Portal 24 Horas',
        'url': 'https://portaldenoticias24horas.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'portal6': {
        'abrangencia': 'Regional',
        'nome': 'Portal 6',
        'url': 'https://portal6.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'zonamnews': {
        'abrangencia': 'Regional',
        'nome': 'Zona da Mata News',
        'url': 'https://www.zonadamatanews.com.br/',
        'prioridade': 'Alta',
        'pontos': '4',
    },
    'vitoriosa': {
        'abrangencia': 'Regional',
        'nome': 'Vitoriosa 9',
        'url': 'https://v9vitoriosa.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'viomundo': {
        'abrangencia': 'Regional',
        'nome': 'Vi o Mundo',
        'url': 'https://www.viomundo.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'valadarestv': {
        'abrangencia': 'Regional',
        'nome': 'Valadares na TV',
        'url': 'https://valadaresnatv.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',
    },
    'tonamidia': {
        'abrangencia': 'Regional',
        'nome': 'To na Mídia',
        'url': 'https://tonamidia.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'tudoemdia': {
        'abrangencia': 'Regional',
        'nome': 'Tudo em Dia',
        'url': 'https://www.tudoemdia.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'terrabrasil': {
        'abrangencia': 'Regional',
        'nome': 'Terra Brasil Notícias',
        'url': 'https://terrabrasilnoticias.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'territorionoticias': {
        'abrangencia': 'Regional',
        'nome': 'Território Notícias',
        'url': 'https://territoriopress.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'portalsucesso': {
        'abrangencia': 'Regional',
        'nome': 'Portal Sucesso',
        'url': 'https://territoriopress.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'sitebarra': {
        'abrangencia': 'Regional',
        'nome': 'Site Barra',
        'url': 'https://sitebarra.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'sinfazfisco_mg': {
        'abrangencia': 'Regional',
        'nome': 'SinfazFisco',
        'url': 'https://sinfazfiscomg.org.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'orion': {
        'abrangencia': 'Local',
        'nome': 'Blog do Orion',
        'url': 'https://www.blogdoorion.com.br/',
        'prioridade': 'Alta',
        'pontos': '2', # não encontrei a pontuação exata
    },
    'jornalminas': {
        'abrangencia': 'Local',
        'nome': 'Jornal Minas',
        'url': 'https://jornalminas.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'radiocdl': {
        'abrangencia': 'Local',
        'nome': 'Rádio CDL FM',
        'url': 'https://cdlfm.com.br/',
        'prioridade': 'Baixa',
        'pontos': '7',
    },
    'smpnovalima': {
        'abrangencia': 'Regional',
        'nome': 'Sempre Nova Lima',
        'url': 'https://semprenovalima.com/',
        'prioridade': 'Baixa',
        'pontos': '5',
    },
    'vetornorte': {
        'abrangencia': 'Local',
        'nome': 'Vetor Norte',
        'url': 'https://vetornortenoticias.com/',
        'prioridade': 'Baixa',
        'pontos': '5',
    },
    'cut_mg': {
        'abrangencia': 'Local',
        'nome': 'CUT (MG)',
        'url': 'https://mg.cut.org.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'mpmg': {
        'abrangencia': 'Local',
        'nome': 'MPMG',
        'url': 'https://www.mpmg.mp.br/portal/',
        'prioridade': 'Baixa',
        'pontos': '7',
    },
    'radioamerica': {
        'abrangencia': 'Regional',
        'nome': 'Rádio América',
        'url': 'https://radioamerica.arquidiocesebh.org.br/noticias/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'radioinconfidencia': {
        'abrangencia': 'Local',
        'nome': 'Rádio Inconfidência',
        'url': 'https://www.inconfidencia.com.br/noticias/',
        'prioridade': 'Baixa',
        'pontos': '7',
    },
    'almg': {
        'abrangencia': 'Regional',
        'nome': 'ALMG',
        'url': 'https://www.almg.gov.br/',
        'prioridade': 'Baixa',
        'pontos': '7',
    },
    'em': {
        'abrangencia': 'Local',
        'nome': 'Estado de Minas',
        'url': 'https://www.em.com.br/',
        'prioridade': 'Alta',
        'pontos': '15',
    },
    'fator': {
        'abrangencia': 'Local',
        'nome': 'O Fator',
        'url': 'https://ofator.com.br/',
        'prioridade': 'Alta',
        'pontos': '7',
    },
    'radio98': {
        'abrangencia': 'Local',
        'nome': 'Rádio 98FM',
        'url': 'https://www.98live.com.br/',
        'prioridade': 'Alta',
        'pontos': '7',
    },
    'spjornal': {
        'abrangencia': 'Regional',
        'nome': 'São Paulo Jornal',
        'url': 'https://saopaulojornal.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'revistaforum': {
        'abrangencia': 'Regional',
        'nome': 'Revista Forum',
        'url': 'https://revistaforum.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'primeirapagina': {
        'abrangencia': 'Regional',
        'nome': 'Primeira Página',
        'url': 'https://primeirapagina.com.br/mato-grosso/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'dentrodetudo': {
        'abrangencia': 'Regional',
        'nome': 'Por Dentro de Tudo',
        'url': 'https://pordentrodetudo.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',
    },
    'patosnoticias': {
        'abrangencia': 'Regional',
        'nome': 'Patos Notícias',
        'url': 'https://patosnoticias.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',
    },
    'revistatempo': {
        'abrangencia': 'Regional',
        'nome': 'Revista Tempo',
        'url': 'https://revistatempo.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'mercadocomum': {
        'abrangencia': 'Regional',
        'nome': 'Mecado Comum',
        'url': 'https://mercadocomum.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'seuexpediente': {
        'abrangencia': 'Regional',
        'nome': 'Seu Expediente',
        'url': 'https://seuexpediente.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',
    },
    'rcwtv': {
        'abrangencia': 'Regional',
        'nome': 'RCWTV',
        'url': 'https://www.rcwtv.com.br/#google_vignette',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'saogoncalo': {
        'abrangencia': 'Regional',
        'nome': 'São Gonçalo Agora',
        'url': 'https://www.saogoncaloagora.com.br/?pl_eleicoes=false',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'tvcaete': {
        'abrangencia': 'Regional',
        'nome': 'TV Caeté',
        'url': 'https://www.tvcaete.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '5',
    },
    'triangulonews': {
        'abrangencia': 'Regional',
        'nome': 'Triângulo News',
        'url': 'https://triangulonews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',
    },
    'tvcbrasil': {
        'abrangencia': 'Regional',
        'nome': 'TVC Brasil',
        'url': 'https://tvcbrasil.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'vamosadiante': {
        'abrangencia': 'Regional',
        'nome': 'Vamos Adiante',
        'url': 'https://vamosadiante.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'redeminas': {
        'abrangencia': 'Regional',
        'nome': 'RedeMinas TV',
        'url': 'https://redeminas.tv/noticias/',
        'prioridade': 'Baixa', 
        'pontos': '10',
    },
    'vdl': {
        'abrangencia': 'Regional',
        'nome': 'Portal VDL',
        'url': 'https://portalvdl.com.br/?pl_eleicoes=false',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'vhnews': {
        'abrangencia': 'Regional',
        'nome': 'VH News',
        'url': 'https://vhnews.com.br/?pl_eleicoes=false',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'webterra': {
        'abrangencia': 'Regional',
        'nome': 'Web Terra',
        'url': 'https://webterra.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'penhanews': {
        'abrangencia': 'Regional',
        'nome': 'Penha News SP',
        'url': 'https://www.penhanews.com.br/brasil',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'primeirojornal': {
        'abrangencia': 'Regional',
        'nome': 'Primeiro Jornal',
        'url': 'https://primeirojornal.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'redegazeta': {
        'abrangencia': 'Regional',
        'nome': 'Rede Gazeta',
        'url': 'https://www.redegazeta.com.br/noticias/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'sindieletro': {
        'abrangencia': 'Regional',
        'nome': 'SindiEletro',
        'url': 'https://sindieletromg.org.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'sindute': {
        'abrangencia': 'Regional',
        'nome': 'SindUTE',
        'url': 'https://sindutemg.org.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'sindepominas': {
        'abrangencia': 'Regional',
        'nome': 'SindepoMinas',
        'url': 'https://www.sindepominas.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'patosja': {
        'abrangencia': 'Regional',
        'nome': 'Patos Já',
        'url': 'https://www.patosja.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'patoshoje': {
        'abrangencia': 'Regional',
        'nome': 'Patos Hoje',
        'url': 'https://patoshoje.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'patosagora': {
        'abrangencia': 'Regional',
        'nome': 'Patos Agora',
        'url': 'https://patosagora.net/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'paracatunews': {
        'abrangencia': 'Regional',
        'nome': 'Paracatu News',
        'url': 'https://paracatunews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'panoramicanews': {
        'abrangencia': 'Regional',
        'nome': 'Panoramica News',
        'url': 'https://panoramicanews.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'santamariense': {
        'abrangencia': 'Regional',
        'nome': 'Plantão Santamariense',
        'url': 'https://plantaosantamariense.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'oeste360': {
        'abrangencia': 'Regional',
        'nome': 'Poder Oeste360',
        'url': 'https://www.oeste360.com/politica#google_vignette',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'oalfenense': {
        'abrangencia': 'Regional',
        'nome': 'O Alfenense',
        'url': 'https://www.oalfenense.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'opniaocaete': {
        'abrangencia': 'Regional',
        'nome': 'Opnião Caeté',
        'url': 'https://www.opiniaocaete.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '5',
    },
    'opopular': {
        'abrangencia': 'Regional',
        'nome': 'O Popular',
        'url': 'https://opopularjm.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'obrasilianistapoli': {
        'abrangencia': 'Regional',
        'nome': 'O Brasilianista',
        'url': 'https://obrasilianista.com.br',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'novojornal': {
        'abrangencia': 'Regional',
        'nome': 'Novo Jornal',
        'url': 'https://www.novojornal.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'nova93fm': {
        'abrangencia': 'Regional',
        'nome': 'Nova 93FM',
        'url': 'https://nova93fm.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'mustach': {
        'abrangencia': 'Regional',
        'nome': 'Mustach',
        'url': 'https://www.mustach.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'mirantebocaina': {
        'abrangencia': 'Regional',
        'nome': 'Mirante da Bocaina',
        'url': 'https://www.mirantedabocaina.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'mgtododia': {
        'abrangencia': 'Regional',
        'nome': 'MG Todo Dia',
        'url': 'https://mgtododia.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'multisom': {
        'abrangencia': 'Regional',
        'nome': 'MultiSom Cataguases',
        'url': 'https://multisomcataguases.com/noticias/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'minasacontece': {
        'abrangencia': 'Regional',
        'nome': 'Minas Acontece',
        'url': 'https://minasacontece.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'mauaagora': {
        'abrangencia': 'Regional',
        'nome': 'Mauá Agora',
        'url': 'https://mauaagora.com.br/category/noticiais/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'manhacunews': {
        'abrangencia': 'Regional',
        'nome': 'Manhuaçu News',
        'url': 'https://www.manhuacunews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'maistopnews': {
        'abrangencia': 'Regional',
        'nome': 'Mais Top News',
        'url': 'https://maistopnews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jfinforma': {
        'abrangencia': 'Regional',
        'nome': 'JF Informa',
        'url': 'https://jfinforma.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'j6live': {
        'abrangencia': 'Regional',
        'nome': 'J6 Live',
        'url': 'https://j6live.com.br/?pl_eleicoes=false',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalspasso': {
        'abrangencia': 'Regional',
        'nome': 'Jornal SPasso',
        'url': 'https://jornalspasso.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalvozativa': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Voz Ativa',
        'url': 'https://jornalvozativa.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'pioneiros': {
        'abrangencia': 'Regional',
        'nome': 'Portal Pioneiros',
        'url': 'https://portalpioneiros.fae.ufmg.br/artigos/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'regionalzao': {
        'abrangencia': 'Regional',
        'nome': 'Portal Regionalzão',
        'url': 'https://regionalzao.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',
    },
    'onorte': {
        'abrangencia': 'Regional',
        'nome': 'Jornal O Norte',
        'url': 'https://onorte.net/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'jornalgvnews': {
        'abrangencia': 'Regional',
        'nome': 'Jornal GV News',
        'url': 'https://www.jornalgvnews.com.br/principal',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalfloripa': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Floripa',
        'url': 'https://jornalfloripa.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalfatoreal': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Fato Real',
        'url': 'https://fatoreal.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'diarioparademinas': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Diário de Pará de Minas',
        'url': 'https://www.jdiario.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornaldeuberaba': {
        'abrangencia': 'Regional',
        'nome': 'Jornal de Uberaba',
        'url': 'https://www.jornaldeuberaba.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'correioregional': {
        'abrangencia': 'Regional',
        'nome': 'Correio Regional',
        'url': 'https://correioregional.net/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'difusao': {
        'abrangencia': 'Regional',
        'nome': 'Portal Difusao Brasil',
        'url': 'https://www.difusaobrasil.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'bairrosnet': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Bairros Net',
        'url': 'https://www.jornalbairrosnet.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'arenadenoticias': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Arena de Notícias',
        'url': 'https://arenadenoticias.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalaraxa': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Araxá',
        'url': 'https://jornalaraxa.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalagora': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Agora',
        'url': 'https://www.agoracomvoce.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalalef': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Alef',
        'url': 'https://jornalalef.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jmonline': {
        'abrangencia': 'Regional',
        'nome': 'JM Online',
        'url': 'https://jmonline.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornaldobrasil': {
        'abrangencia': 'Regional',
        'nome': 'Jornal do Brasil',
        'url': 'https://www.jb.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '10',  
    },
    'itabiranoticia': {
        'abrangencia': 'Regional',
        'nome': 'Itabira Notícia',
        'url': 'https://itabiranoticia.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'itabiranet': {
        'abrangencia': 'Regional',
        'nome': 'Itabira Net',
        'url': 'https://itabiranet.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'independentenoticias': {
        'abrangencia': 'Regional',
        'nome': 'Independente Notícias',
        'url': 'https://www.portalindependentenoticia.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'imparcialnews': {
        'abrangencia': 'Regional',
        'nome': 'Imparcial News',
        'url': 'https://imparcialnews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'impactto': {
        'abrangencia': 'Regional',
        'nome': 'Portal Impactto',
        'url': 'https://portalimpactto.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'hoteliernews': {
        'abrangencia': 'Regional',
        'nome': 'Portal Hotelier News',
        'url': 'https://www.hoteliernews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'horadopovo': {
        'abrangencia': 'Regional',
        'nome': 'Portal Hora do Povo',
        'url': 'https://horadopovo.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'portaldoholanda': {
        'abrangencia': 'Regional',
        'nome': 'Portal de Holanda',
        'url': 'https://www.portaldoholanda.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gospelprime': {
        'abrangencia': 'Regional',
        'nome': 'Gospel Prime',
        'url': 'https://www.gospelprime.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gp1': {
        'abrangencia': 'Regional',
        'nome': 'Portal GP1',
        'url': 'https://www.gp1.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalggn': {
        'abrangencia': 'Regional',
        'nome': 'Jornal GGN',
        'url': 'https://jornalggn.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'grnews': {
        'abrangencia': 'Regional',
        'nome': 'GRNews',
        'url': 'https://grnews.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gentedeopniao': {
        'abrangencia': 'Regional',
        'nome': 'Gente de Opnião',
        'url': 'https://www.gentedeopiniao.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'portalgerais': {
        'abrangencia': 'Regional',
        'nome': 'Portal Gerais',
        'url': 'https://portalgerais.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gazetaoeste': {
        'abrangencia': 'Regional',
        'nome': 'Gazeta do Oeste',
        'url': 'https://g37.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'guiamuriae': {
        'abrangencia': 'Regional',
        'nome': 'Guia Muriaé',
        'url': 'https://www.guiamuriae.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gazetanorte': {
        'abrangencia': 'Regional',
        'nome': 'Gazeta Norte Mineira',
        'url': 'https://gazetanm.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gazetamuriae': {
        'abrangencia': 'Regional',
        'nome': 'Gazeta de Muriaé',
        'url': 'https://gazetademuriae.com.br/noticia/lista',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'correiotriangulo': {
        'abrangencia': 'Regional',
        'nome': 'Correio do Triângulo',
        'url': 'https://www.correiodotriangulo.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'campobelo': {
        'abrangencia': 'Regional',
        'nome': 'Campo Belo em Foco',
        'url': 'https://www.campobeloemfoco.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'jornalgeraes': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Geraes(Portal Galilé)',
        'url': 'https://jornalgeraes.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'gazetamunicipio': {
        'abrangencia': 'Regional',
        'nome': 'Gazeta dos Municípios',
        'url': 'https://gazetadosmunicipios.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'defatoonline': {
        'abrangencia': 'Regional',
        'nome': 'Defato Online',
        'url': 'https://defatoonline.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'folhapatense': {
        'abrangencia': 'Regional',
        'nome': 'Folha Patense',
        'url': 'https://www.folhapatense.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '4',  
    },
    'folhadopovo': {
        'abrangencia': 'Regional',
        'nome': 'Folha do Povo Itatiaiuçu',
        'url': 'https://www.folhapovoitatiaiucu.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'folhapovoitauna': {
        'abrangencia': 'Regional',
        'nome': 'Folha do Povo Itaúna',
        'url': 'https://www.folhapovoitauna.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'folhasetelagoas': {
        'abrangencia': 'Regional',
        'nome': 'Folha de Sete Lagoas',
        'url': 'https://folhadesetelagoas.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'esquerdadiario': {
        'abrangencia': 'Regional',
        'nome': 'Esquerda Diário',
        'url': 'https://www.esquerdadiario.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'ermida_mg': {
        'abrangencia': 'Regional',
        'nome': 'Ermida MG',
        'url': 'https://ermidamg.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'dco': {
        'abrangencia': 'Regional',
        'nome': 'Diário Causa Operária',
        'url': 'https://causaoperaria.org.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'folhasabara': {
        'abrangencia': 'Regional',
        'nome': 'Folha de Sabará',
        'url': 'https://folhadesabara.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '5',  
    },
    'folhacentrosul': {
        'abrangencia': 'Regional',
        'nome': 'Folha Centro Sul',
        'url': 'https://folhacentrosul.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'esbrasil': {
        'abrangencia': 'Regional',
        'nome': 'ES Brasil',
        'url': 'https://esbrasil.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'euqueroinvestir': {
        'abrangencia': 'Regional',
        'nome': 'Eu Quero Investir',
        'url': 'https://euqueroinvestir.com/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'diarioouropreto': {
        'abrangencia': 'Regional',
        'nome': 'Diário de Ouro Preto',
        'url': 'https://www.diariodeouropreto.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'diariogoias': {
        'abrangencia': 'Regional',
        'nome': 'Diário de Góias',
        'url': 'https://diariodegoias.com.br/',
        'prioridade': 'Baixa', 
        'pontos': '2',  
    },
    'centrodomundo': {
        'abrangencia': 'Regional',
        'nome': 'Diário Centro do Mundo',
        'url': 'https://www.diariodocentrodomundo.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'inteligenciabrasil': {
        'abrangencia': 'Regional',
        'nome': 'Inteligência Brasil',
        'url': 'https://ibi.ong.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'diariouberlandia': {
        'abrangencia': 'Regional',
        'nome': 'Diário de Uberlândia',
        'url': 'https://diariodeuberlandia.com.br/',
        'prioridade': 'Baixa',
        'pontos': '4',  
    },
    'sindsaude': {
        'abrangencia': 'Regional',
        'nome': 'Sind-Saúde (MG)',
        'url': 'https://sindsaudemg.org.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'folhavitoria': {
        'abrangencia': 'Regional',
        'nome': 'Folha Vitória',
        'url': 'https://www.folhavitoria.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'cadernopolitico': {
        'abrangencia': 'Regional',
        'nome': 'Caderno Político',
        'url': 'https://cadernopolitico.com/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'cidadenarede': {
        'abrangencia': 'Regional',
        'nome': 'Cidade na Rede',
        'url': 'https://cidadenarede.net/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'conexaoitajuba': {
        'abrangencia': 'Regional',
        'nome': 'Conexão Itajuba',
        'url': 'https://conexaoitajuba.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'chapadagrande': {
        'abrangencia': 'Regional',
        'nome': 'Chapada Grande',
        'url': 'https://www.chapadagrande.com/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'jornalclassivale': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Classivale',
        'url': 'https://jornalclassivale.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'caparao': {
        'abrangencia': 'Regional',
        'nome': 'Portal Caparaó',
        'url': 'https://www.portalcaparao.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'correiosul': {
        'abrangencia': 'Regional',
        'nome': 'Portal Correio do Sul',
        'url': 'https://portalc1.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'cafemutuca': {
        'abrangencia': 'Regional',
        'nome': 'Café Mutuca',
        'url': 'https://cafemutuca.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'correiouberlandia': {
        'abrangencia': 'Regional',
        'nome': 'Correo de Uberlândia',
        'url': 'https://jornalcorreiodeuberlandia.com.br/',
        'prioridade': 'Baixa',
        'pontos': '4',  
    },
    'bombabomba': {
        'abrangencia': 'Regional',
        'nome': 'Portal Bomba Bomba',
        'url': 'https://bombabomba.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'betancity': {
        'abrangencia': 'Regional',
        'nome': 'Betan City',
        'url': 'https://betancity.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'alouberlandia': {
        'abrangencia': 'Regional',
        'nome': 'Alô Uberlândia',
        'url': 'https://www.alouberlandia.com/',
        'prioridade': 'Baixa',
        'pontos': '4',  
    },
    'vozdopovo': {
        'abrangencia': 'Regional',
        'nome': 'A Voz do Povo',
        'url': 'https://avozdopovo.org/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'agita': {
        'abrangencia': 'Regional',
        'nome': 'Portal Agita',
        'url': 'https://portalagita.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'ancoranews': {
        'abrangencia': 'Regional',
        'nome': 'Âncora News',
        'url': 'http://ancoranews.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'antenados': {
        'abrangencia': 'Regional',
        'nome': 'Portal Antenados',
        'url': 'https://portalantenados.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'asthe_mg': {
        'abrangencia': 'Regional',
        'nome': 'Asthe MG',
        'url': 'https://asthemg.org.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'aspra': {
        'abrangencia': 'Regional',
        'nome': 'Portal Aspra',
        'url': 'https://aspra.org.br/portal/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'noticiaonline': {
        'abrangencia': 'Regional',
        'nome': 'A Notícia Online',
        'url': 'https://anoticiaregional.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'agrolink': {
        'abrangencia': 'Regional',
        'nome': 'Agrolink',
        'url': 'https://www.agrolink.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'aconteceuvale': {
        'abrangencia': 'Regional',
        'nome': 'Aconteceu no Vale',
        'url': 'https://aconteceunovale.com.br/portal/',
        'prioridade': 'Baixa',
        'pontos': '4',  
    },
    'apuracaominas': {
        'abrangencia': 'Regional',
        'nome': 'Apuração Minas',
        'url': 'https://www.apuracaominas.com/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'aredacao': {
        'abrangencia': 'Regional',
        'nome': 'A Redação',
        'url': 'https://www.aredacao.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'abcdmaior': {
        'abrangencia': 'Regional',
        'nome': 'ABCD Maior',
        'url': 'https://abcdmaior.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'politicalivre': {
        'abrangencia': 'Regional',
        'nome': 'Política Livre',
        'url': 'https://politicalivre.com.br/#gsc.tab=0',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'blogpedlowski': {
        'abrangencia': 'Regional',
        'nome': 'Blog Pedlowski',
        'url': 'https://blogdopedlowski.com/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'blogmarcos': {
        'abrangencia': 'Regional',
        'nome': 'Blog do Marcos Almeida',
        'url': 'https://marcosalmeidalocutor.wordpress.com/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'bloghp': {
        'abrangencia': 'Regional',
        'nome': 'Blog do HP',
        'url': 'https://www.blogdohp.com/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'divinews': {
        'abrangencia': 'Regional',
        'nome': 'Divinews',
        'url': 'https://divinews.com/',
        'prioridade': 'Baixa',
        'pontos': '6',  
    },
    'difusora95fm': {
        'abrangencia': 'Regional',
        'nome': 'Difusora 95 FM',
        'url': 'https://difusora95.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'vox97fm': {
        'abrangencia': 'Regional',
        'nome': 'Vox 97 FM',
        'url': 'https://vox97.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'radio93fm': {
        'abrangencia': 'Regional',
        'nome': 'Rádio 93 FM',
        'url': 'https://radio93.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'radio104fm': {
        'abrangencia': 'Regional',
        'nome': 'Rádio 104 FM',
        'url': 'https://104fm.net.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'tvredemais': {
        'abrangencia': 'Regional',
        'nome': 'TV Rede Mais',
        'url': 'https://redemais.tv.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'tvparanaiba': {
        'abrangencia': 'Regional',
        'nome': 'TV Paranaíba',
        'url': 'https://tvparanaiba.com.br/',
        'prioridade': 'Média',
        'pontos': '10',  
    },
    'tvpocos': {
        'abrangencia': 'Regional',
        'nome': 'TV Poços',
        'url': 'https://tvpocos.com.br/',
        'prioridade': 'Baixa',
        'pontos': '3',  
    },
    'gazetavarginha': {
        'abrangencia': 'Regional',
        'nome': 'Gazeta de Varginha',
        'url': 'https://www.gazetadevarginha.com.br/',
        'prioridade': 'Baixa',
        'pontos': '4',  
    },
    'cidadesminerais': {
        'abrangencia': 'Regional',
        'nome': 'Cidades e Minerais',
        'url': 'https://cidadeseminerais.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'barrosoemdia': {
        'abrangencia': 'Regional',
        'nome': 'Barroso em Dia',
        'url': 'https://barrosoemdia.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'balcaonews': {
        'abrangencia': 'Regional',
        'nome': 'Balcão News',
        'url': 'https://balcaonews.com.br/',
        'prioridade': 'Baixa',
        'pontos': '7',  
    },
    'atilalemos': {
        'abrangencia': 'Regional',
        'nome': 'Átila Lemos',
        'url': 'https://atilalemos.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'g1_coeste': {
        'abrangencia': 'Regional',
        'nome': 'G1 Centro Oeste',
        'url': 'https://g1.globo.com/mg/centro-oeste/',
        'prioridade': 'Alta',
        'pontos': '10',  
    },
    'g1_gdmg': {
        'abrangencia': 'Regional',
        'nome': 'G1 Grande Minas',
        'url': 'https://g1.globo.com/mg/grande-minas/',
        'prioridade': 'Alta',
        'pontos': '10',  
    },
    'g1_sulmg': {
        'abrangencia': 'Regional',
        'nome': 'G1 Sul de Minas',
        'url': 'https://g1.globo.com/mg/sul-de-minas/',
        'prioridade': 'Alta',
        'pontos': '10',  
    },
    'g1_triangulo': {
        'abrangencia': 'Regional',
        'nome': 'G1 Triângulo Mineiro',
        'url': 'https://g1.globo.com/mg/triangulo-mineiro/',
        'prioridade': 'Alta',
        'pontos': '10',  
    },
    'g1_valesmg': {
        'abrangencia': 'Regional',
        'nome': 'G1 Vales de MG',
        'url': 'https://g1.globo.com/mg/vales-mg/',
        'prioridade': 'Alta',
        'pontos': '10',  
    },
    'g1_zmata': {
        'abrangencia': 'Regional',
        'nome': 'G1 Zona da Mata',
        'url': 'https://g1.globo.com/mg/zona-da-mata/',
        'prioridade': 'Alta',
        'pontos': '10',  
    },
    'tribuna': {
        'abrangencia': 'Regional',
        'nome': 'Tribuna de Minas',
        'url': 'https://tribunademinas.com.br/',
        'prioridade': 'Alta',
        'pontos': '8',  
    },
    'itatiaia_jf': {
        'abrangencia': 'Regional',
        'nome': 'Itatiaia Juiz de Fora',
        'url': 'https://radioitatiaiajf.com.br/',
        'prioridade': 'Média',
        'pontos': '4',  
    },
    'itatiaia_op': {
        'abrangencia': 'Regional',
        'nome': 'Itatiaia Ouro Preto',
        'url': 'https://www.itatiaia.com.br/ouropreto',
        'prioridade': 'Média',
        'pontos': '2',  
    },
    'diariocaratinga': {
        'abrangencia': 'Regional',
        'nome': 'Diário de Caratinga',
        'url': 'https://diariodecaratinga.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'jcnoticias': {
        'abrangencia': 'Regional',
        'nome': 'JC Notícias',
        'url': 'https://www.jcnoticias.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'jornalintegracao': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Integração (Leia Fácil)',
        'url': 'https://leiafacil.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',  
    },
    'alterosa_znmata': {
        'abrangencia': 'Regional',
        'nome': 'TV Alterosa - Zona da Mata',
        'url': 'https://www.alterosa.com.br/programas/alterosa-em-alerta-zona-da-mata/',
        'prioridade': 'Média',
        'pontos': '8',  
    },
    'alterosa_sulminas': {
        'abrangencia': 'Regional',
        'nome': 'TV Alterosa - Sul de Minas',
        'url': 'https://www.alterosa.com.br/programas/alterosa-em-alerta-dv/',
        'prioridade': 'Média',
        'pontos': '8',  
    },
    'cidadeipatinga': {
        'abrangencia': 'Regional',
        'nome': 'Portal Cidade Ipatinga',
        'url': 'https://ipatinga.portaldacidade.com/noticias',
        'prioridade': 'Baixa',
        'pontos': '4',  
    },
    'diarioaraxa': {
        'abrangencia': 'Regional',
        'nome': 'Diário de Araxá',
        'url': 'https://www.diariodearaxa.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'valoreconomico': {
        'abrangencia': 'Nacional',
        'nome': 'Valor Econômico',
        'url': 'https://valor.globo.com/',
        'prioridade': 'Alta',
        'pontos': '30',
    },
    'diariocomercio': {
        'abrangencia': 'Local',
        'nome': 'Diário do Comércio',
        'url': 'https://diariodocomercio.com.br/',
        'prioridade': 'Alta',
        'pontos': '7',
    },
    'sinmed_mg': {
        'abrangencia': 'Regional',
        'nome': 'Sinmed MG',
        'url': 'https://sinmedmg.org.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'jornaldosvales': {
        'abrangencia': 'Regional',
        'nome': 'Jornal dos Vales',
        'url': 'https://jornaldosvales.com.br/',
        'prioridade': 'Baixa',
        'pontos': '4',
    },
    'acessacom': {
        'abrangencia': 'Regional',
        'nome': 'Acessa.com',
        'url': 'https://www.acessa.com/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'queroinvestir': {
        'abrangencia': 'Regional',
        'nome': 'Eu Quero Investir',
        'url': 'https://euqueroinvestir.com/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'valeitajai': {
        'abrangencia': 'Regional',
        'nome': 'Vale do Itajaí Notícias',
        'url': 'https://valedoitajainoticias.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'sindpol_mg': {
        'abrangencia': 'Regional',
        'nome': 'Sindpol MG',
        'url': 'htps://sindpolmg.org.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'andradas': {
        'abrangencia': 'Regional',
        'nome': 'Portal da Cidade (Andradas)',
        'url': 'https://andradas.portaldacidade.com/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'brumadinho': {
        'abrangencia': 'Regional',
        'nome': 'Portal da Cidade (Brumadinho)',
        'url': 'https://brumadinho.portaldacidade.com/',
        'prioridade': 'Baixa',
        'pontos': '5',
    },
    'ipatinga': {
        'abrangencia': 'Regional',
        'nome': 'Portal da Cidade (Ipatinga)',
        'url': 'https://ipatinga.portaldacidade.com/noticias',
        'prioridade': 'Baixa',
        'pontos': '4',
    },
    'terradocafe': {
        'abrangencia': 'Regional',
        'nome': 'Terra do Café',
        'url': 'https://www.aterradocafe.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'fmjequitiba': {
        'abrangencia': 'Regional',
        'nome': 'Cidade FM Jequitibá',
        'url': 'https://www.cidadefmjequitiba.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'cearapauta': {
        'abrangencia': 'Regional',
        'nome': 'Ceará em Pauta',
        'url': 'https://cearaempauta.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'jornalcorreio': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Correio',
        'url': 'https://portalcorreio.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'mpa': {
        'abrangencia': 'Regional',
        'nome': 'Sistema MPA',
        'url': 'https://www.sistemampa.com.br/',
        'prioridade': 'Alta',
        'pontos': '6',
    },
    'bhaz': {
        'abrangencia': 'Local',
        'nome': 'BHAZ',
        'url': 'https://bhaz.com.br/',
        'prioridade': 'Alta',
        'pontos': '12',
    },
    'jornalopcao': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Opção',
        'url': 'https://www.jornalopcao.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'folhademinas': {
        'abrangencia': 'Regional',
        'nome': 'O Folha de Minas',
        'url': 'https://ofolhademinas.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'ultimasformiga': {
        'abrangencia': 'Regional',
        'nome': 'Últimas Notícias - Formiga',
        'url': 'https://ultimasnoticias.inf.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    },
    'maisminas': {
        'abrangencia': 'Regional',
        'nome': 'Jornal Mais Minas',
        'url': 'https://jornalmaisminas.com.br/',
        'prioridade': 'Baixa',
        'pontos': '2',
    }
}
